repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Django Tests
        entry: python manage.py test
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]

      - id: flake8
        name: Flake8 Linting
        entry: flake8
        language: system
        types: [python]
        stages: [commit]
